# Generated by Django 6.0.3 on 2026-03-29 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='maintenance_qr',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_qrs/'),
        ),
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=200)),
                ('proof_image', models.ImageField(upload_to='payment_proofs/')),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified (Auto)'), ('flagged', 'Flagged (Date Mismatch)'), ('approved', 'Approved (Manual)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
