# Generated by Django 6.0.3 on 2026-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitecode_maintenance_qr_paymentproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyMaintenanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_name', models.CharField(max_length=200, unique=True)),
                ('maintenance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parking_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=15, help_text='Day of the month when late fee starts (e.g. 15)')),
                ('late_fee_percentage', models.PositiveSmallIntegerField(default=21, help_text='Percentage of late fee tax (e.g. 21)')),
            ],
        ),
    ]
