# Generated by Django 6.0.3 on 2026-03-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_societymaintenancesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='extracted_payee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='societymaintenancesettings',
            name='expected_payee_name',
            field=models.CharField(blank=True, help_text='Exact name that appears on your QR/Bank account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='societymaintenancesettings',
            name='maintenance_qr',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance_qrs/'),
        ),
    ]
