# Generated by Django 6.0.3 on 2026-03-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_paymentproof_extracted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='extracted_sender',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
