# Generated by Django 6.0.3 on 2026-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentproof_extracted_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='extracted_account_digits',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='societymaintenancesettings',
            name='expected_payee_account',
            field=models.CharField(blank=True, help_text='Last 4 digits of your bank account (e.g. 5200)', max_length=10, null=True),
        ),
    ]
