# Generated by Django 6.0.3 on 2026-03-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_paymentproof_extracted_account_digits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproof',
            name='extracted_payee',
        ),
        migrations.RemoveField(
            model_name='societymaintenancesettings',
            name='expected_payee_name',
        ),
    ]
