# Generated by Django 6.0.3 on 2026-03-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_paymentproof_extracted_payee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societymaintenancesettings',
            name='parking_charge',
        ),
        migrations.RemoveField(
            model_name='societymaintenancesettings',
            name='water_charge',
        ),
    ]
