# Generated by Django 6.0.3 on 2026-04-05 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_societymaintenancesettings_parking_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'resident_role': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rentals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('rental', 'Rental')], default='owner', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='RentalChargeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_day', models.PositiveSmallIntegerField(default=5, help_text='Day of month when rent is due')),
                ('late_fee_percentage', models.PositiveSmallIntegerField(default=10, help_text='Late fee percentage')),
                ('upi_id', models.CharField(blank=True, help_text="Owner's UPI ID for rent collection", max_length=100, null=True)),
                ('upi_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rent_qr', models.ImageField(blank=True, null=True, upload_to='rent_qrs/')),
                ('notes', models.TextField(blank=True, help_text='Any notes for the rental (e.g. unit details)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(limit_choices_to={'resident_role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='rental_charge_settings', to=settings.AUTH_USER_MODEL)),
                ('rental_user', models.OneToOneField(blank=True, limit_choices_to={'resident_role': 'rental'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rental_charge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
