# Generated by Django 6.0.3 on 2026-04-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_user_owner_user_resident_role_rentalchargesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalchargesettings',
            name='late_fee_percentage',
        ),
        migrations.RemoveField(
            model_name='rentalchargesettings',
            name='upi_id',
        ),
        migrations.RemoveField(
            model_name='rentalchargesettings',
            name='upi_name',
        ),
        migrations.AddField(
            model_name='rentalchargesettings',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text='Name on the Bank Account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rentalchargesettings',
            name='account_number',
            field=models.CharField(blank=True, help_text="Owner's Bank Account Number", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rentalchargesettings',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC Code', max_length=20, null=True),
        ),
    ]
