# Generated by Django 6.0.3 on 2026-04-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_rentalchargesettings_late_fee_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalchargesettings',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='rentalchargesettings',
            name='ifsc_code',
        ),
    ]
