# Generated by Django 6.0.3 on 2026-04-05 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_rentalchargesettings_account_holder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentPaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='rent_proofs/')),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_account_digits', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified (Auto)'), ('flagged', 'Flagged (Mismatch)'), ('approved', 'Approved (Manual)'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_rent_proofs', to=settings.AUTH_USER_MODEL)),
                ('rental_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_proofs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
