# Generated by Django 6.0.3 on 2026-04-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rentpaymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_welcome',
            field=models.BooleanField(default=False),
        ),
    ]
