# Generated by Django 6.0.3 on 2026-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('secretary', 'Secretary'), ('company', 'Company'), ('resident', 'Residential'), ('watchman', 'Watchman')], default='resident', max_length=20),
        ),
    ]
