# Generated by Django 6.0.3 on 2026-03-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visitor_type', models.CharField(choices=[('Guest', 'Guest'), ('Delivery', 'Delivery')], max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Inside', max_length=50)),
            ],
        ),
    ]
