# Generated by Django 6.0.3 on 2026-04-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.AddField(
            model_name='visitor',
            name='recorded_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/vehicles/'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_photo',
            field=models.ImageField(blank=True, null=True, upload_to='visitors/photos/'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Delivery', 'Delivery')], default='Guest', max_length=50),
        ),
    ]
