# Generated by Django 6.0.3 on 2026-04-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_delete_expense_visitor_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
