# Generated by Django 6.0.3 on 2026-03-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
