# Generated by Django 6.0.3 on 2026-03-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0002_bill_payment_date_bill_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='amount',
            new_name='total_amount',
        ),
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='is_late_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='maintenance_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='parking_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='water_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
