# Generated by Django 6.0.3 on 2026-03-30 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_rename_amount_bill_total_amount_bill_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='parking_charge',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='water_charge',
        ),
    ]
